### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by Rainbell129** [Johnson0907/obsidian-daily-notes-viewer#1]
Is it possible to filter out only the contents under a specific heading in the daily note viewer? That'll be extremely helpful!

**Comment by DryIce1** [comment]
Yes, this is a great idea!

I imagine many users have headings such as
- journalling and free ideas
- habit tracking, statistics
- subjects related to specific areas of life - e.g. Work, school, family...

Being able to quickly switch (using a hotkey) between each header/section of the journal (reveal habit tracking section, reveal work section, show all sections) would be amazing.

**Comment by HEmile** [comment]
Looks like this is implemented in the settings?

**Comment by dmkravets** [comment]
It seems regardless of whether I look at the Viewer in edit or reading mode, I cannot edit the daily notes. Am I doing something wrong? If I'm not, can I request that as a feature: to be able to edit the daily notes in the Viewer? Thanks!

**Comment by Johnson0907** [comment]
Sorry, you can only view but not edit in the viewer.
Because the plugin just arranges ![daily notes] and writes it to a page.
You can click the title of a daily note in the viewer to jump to the page of a daily note for editing.
