### ISSUE TITLE
Bug: Does not respect locale ordering

### ISSUE THREAD

**Issue by HEmile** [Johnson0907/obsidian-daily-notes-viewer#5]
It does not respect the locale. Ie, I use DD-MM-YYYY, however, it seems to sort it (reversed) alphanumerically:

![image](https://user-images.githubusercontent.com/1289165/160149339-a741868e-05e8-4619-9263-f2ff80acc7a1.png)

You can get the locale to ensure the right ordering.

**Comment by Johnson0907** [comment]
Thanks for your report. It is recommended to use the "YYYY-MM-DD" format temporarily. I will improve the date sorting.

**Comment by Johnson0907** [comment]
This bug has been fixed in the latest version.

**Comment by HEmile** [comment]
Thanks, this seems to work :)
