### ISSUE TITLE
FR: Define period range to display

### ISSUE THREAD

**Issue by HEmile** [Johnson0907/obsidian-daily-notes-viewer#6]
I like the idea of this plugin a lot, actually I had a templater script to do something similar but this could be more convenient. 
However, it would be great if I could define a period range for displaying the daily notes, ie if there's a modal that says: Show me the notes between *date X* and *date Y* with *this heading*.

**Comment by Johnson0907** [comment]
Thanks for your FR. “Displaying daily notes for a certain period” is already on the roadmap.

**Comment by Johnson0907** [comment]
"Displaying daily notes for a certain period" is already supported, please update to the latest version.
Tips: plugin settings => filter => choose "range" => set "start date" and "end date"

**Comment by HEmile** [comment]
Thanks, this works great! :)
