### ISSUE TITLE
Hide future date annotations

### ISSUE THREAD

**Issue by KierPrev** [Johnson0907/obsidian-daily-notes-viewer#7]
Sometimes you make several annotations or tasks on future days, but you don't want to see it on the daily notes viewer (see Roam, Logseq, Remnote, etc.)

**Comment by Johnson0907** [comment]
Thanks. This is a good suggestion and I will add this feature.

**Comment by KierPrev** [comment]
Thanks!

**Comment by Johnson0907** [comment]
"Hide future daily notes" is already supported, please update to the latest version.
Tips: plugin settings => filter => choose "recent" => display future daily notes: off

**Comment by KierPrev** [comment]
Omg, that was so fast, thank you!
I think this feature will be essential for people that plan tasks and leave notes on future dates.
